#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const input = process.argv[2] || fileURLToPath(new URL('./diagram-from-v06.svg', import.meta.url));
const output = process.argv[3] || fileURLToPath(new URL('./diagram-v08-single-flow.svg', import.meta.url));

let svg = await readFile(input, 'utf8');

// Only replace visible text-node payloads. System field names remain in parentheses so
// product and engineering can still locate the same value in traces and protocols.
const replacements = new Map([
  ['0 · 先确定读法和证据边界', '豆包汽车｜语音用户请求到真实结果｜完整业务架构'],
  ['VERSION · 2026-09-03', '内容口径｜2026-09-03'],
  ['1 · 单次语音 Query 的完整运行时主链', '1｜一次语音用户请求的完整运行主链'],
  ['严格从左到右：感知与观察 → 注意/介入 → 输入与 Context → Planner/Director → 确定性门禁 → Tool/Agent 与执行器 → 回读/反馈/表达。', '严格从左到右：感知与观察 → 注意/介入 → 输入与上下文 → 规划决策器 → 确定性门禁 → 工具/任务代理与执行器 → 回读/反馈/表达。'],
  ['BLUE = REQUEST · GREEN = RESULT', '蓝色＝用户请求与动作下发｜绿色＝真实结果回流'],
  ['端侧：先把声音变成带身份与时间的 user_query', '端侧：先把声音变成带身份与时间的用户请求（user_query）'],
  ['输入治理目标与 Context', '输入治理与上下文'],
  ['Input Manager 接入范围待 Trace；Context 旁路维护、决策前注入', '输入管理接入范围待链路验真；上下文旁路维护、决策前注入'],
  ['理解与计划｜Planner = Director', '理解与计划｜Planner 与 Director 是同一决策模块'],
  ['模型 JSON 先经工程门禁，才允许下发', '模型结构化结果先经工程门禁，才允许下发'],
  ['Tool / Agent 与 Executor', '工具 / 任务代理与执行器'],
  ['回读 → feedback → 再决策；听到、看到、真的发生', '回读 → 执行反馈 → 再决策；听到、看到、真的发生'],
  ['2A · Perception / Attention / Identity 细化', '2A｜感知 / 注意 / 身份细化'],
  ['飞书长期架构补齐“感知、注意、身份”职责；其中机制状态仍按当前 / 历史 / Trace 分开标。', '长期架构补齐感知、注意、身份职责；机制状态仍按当前 / 历史 / 待链路验真分开标。'],
  ['EDGE FIRST', '先看车端感知'],
  ['2B · Context / Memory 细化', '2B｜上下文 / 记忆细化'],
  ['Context 不是信息仓库，而是“按本轮目标筛选、隔离、裁决、压缩后交给 Planner 的单次视图”。', '上下文不是信息仓库，而是按本轮目标筛选、隔离、裁决、压缩后交给规划决策器的单次事实视图。'],
  ['FACTS BEFORE REASONING', '先保证事实，再谈模型推理'],
  ['2C · Planner AI 能力 + Example DAG', '2C｜规划决策器 AI 能力＋复合案例依赖图'],
  ['AI 的核心不只是意图分类：它要持续根据新事实、新结果和未完成目标，重建下一步最小可执行计划。', 'AI 的核心不只是意图分类：它要持续根据新事实、新结果和未完成目标，重建下一步最小可执行计划。'],
  ['THINK → ACT → OBSERVE → THINK', '判断 → 行动 → 观察 → 再判断'],
  ['3 · Tool / Agent / Executor 能力层｜27 个当前 SP 工具逐项展开', '3｜工具 / 任务代理 / 执行器能力层｜27 个工具逐项展开'],
  ['上方 DOWNLINK 只下发一个已通过门禁的 ToolCall / AgentGoal；下方 RESULT BUS 只汇聚真实 result / state / error / artifact。', '动作下行总线只下发已通过门禁的工具调用或任务代理目标；结果总线只汇聚真实结果、状态、错误与产物。'],
  ['NO action_list → done SHORTCUT', '禁止：动作清单直接等于完成'],
  ['先分清 Tool / Agent / Executor / Result 的职责', '先分清工具、任务代理、执行器与结果的职责'],
  ['POI → Route → Navi 存在明确前置依赖', '地点 → 路线 → 导航存在明确前置依赖'],
  ['3G · Executor / Result Loop', '3G｜执行器与结果闭环'],
  ['4 · Goal / Advisor / Trigger / VLM / Task 异步链', '4｜目标 / 顾问 / 触发器 / 视觉模型 / 任务异步链'],
  ['这三块通过命名 Portal 接入主链，避免用跨越整张图的长线。当前 Goal 与 WIP Task 必须分版本；VLM 只负责描述，不直接调工具。', '三条支路通过明确入口接回主链。当前目标链与建设中任务链必须分版本；视觉模型只负责描述，不直接调用工具。'],
  ['ORANGE = CURRENT ASYNC · PURPLE = WIP', '橙色＝当前异步目标链｜紫色虚线＝建设中任务链'],
  ['4A · 当前 / 迁移态｜Goal List + Advisor + Trigger', '4A｜当前 / 迁移态：目标队列＋顾问＋触发器'],
  ['CURRENT / MIGRATION', '当前 / 迁移态'],
  ['4B · VLM 动态感知子链', '4B｜视觉语言模型（VLM）动态感知子链'],
  ['动态观察目标以 full list 下发；端侧采样形成报告；Trigger 再做业务条件匹配。', '动态观察目标以全量观察清单下发；端侧采样形成报告；触发器再做业务条件匹配。'],
  ['VLM = OBSERVER', '视觉模型＝客观观察者'],
  ['4C · Task Service 目标态', '4C｜任务服务（Task Service）目标态'],
  ['Task 管生命周期和证据；沿用原 Flow → Planner → Tool/Agent，不建设第二个 Planner。', '任务服务管理生命周期和证据；仍沿用原流程 → 同一规划决策器 → 工具/任务代理，不建设第二个大脑。'],
  ['WIP · NOT CURRENT SP', '建设中｜不属于当前提示词协议'],
  ['真正的 AI 产品能力 = 能沿一条 Trace 判断：是输入错、Context 错、Planner 推理错、工具契约错、执行失败，还是完成证据不足。', '真正的 AI 产品能力＝能沿一条链路追踪判断：是输入错、上下文错、模型推理错、工具契约错、执行失败，还是完成证据不足。'],
  ['MEASURE THE USER GOAL', '用用户完整目标做分母'],

  ['Voice Front-end｜声音 → user_query', '语音前端｜声音 → 用户请求（user_query）'],
  ['Attention + Routing｜是否介入 / 端云唯一裁决', '注意与路由｜是否介入 / 端云唯一裁决'],
  ['Input Manager（治理目标）+ Context View', '输入管理（治理目标）＋上下文视图'],
  ['Planner / Director｜AI 决策大脑', '规划决策器（Planner / Director）｜AI 决策大脑'],
  ['Decision Bridge｜解析、校验、守卫、编排', '确定性决策桥｜解析、校验、守卫、编排'],
  ['Tool / Agent / Executor｜真正做事', '工具 / 任务代理 / 执行器｜真正做事'],
  ['Result Loop + Response｜工具回流 / 生效验收', '结果回流与响应｜工具反馈 / 生效验收'],
  ['EDGE', '车端'],
  ['EDGE + CLOUD', '车端＋云端'],
  ['CLOUD · PARTIAL AS-IS', '云端｜部分为当前现状'],
  ['DETERMINISTIC', '确定性工程层'],
  ['EDGE + CLOUD + ECOSYSTEM', '车端＋云端＋生态服务'],
  ['PROTOCOL AS-IS · E2E TO VERIFY', '当前协议｜端到端待验真'],
  ['需Trace', '待链路验真'],
  ['当前SP', '当前提示词协议'],

  ['PCM + wake state', '原始音频＋唤醒状态'],
  ['mic + wake / no-wake', '麦克风＋唤醒 / 免唤醒'],
  ['AEC / NS / beam', '回声消除 / 降噪 / 波束定位'],
  ['seat + candidate id', '座位＋说话人候选'],
  ['VAD + Barge-in', '人声起止＋插话打断'],
  ['start / end / interrupt', '起点 / 终点 / 打断'],
  ['partial → final', '增量文字 → 最终文字'],
  ['weak / no-network', '弱网 / 无网'],
  ['IDENTITY / SEAT ↓', '身份 / 座位信息'],
  ['AUDIO TRACE ↓', '音频追踪信息'],
  ['来自 Voice / UI / event', '来自语音 / 界面 / 系统事件'],
  ['scene + latest state', '场景＋最新端侧状态'],
  ['what is running', '当前正在运行什么'],
  ['Listen / Reject / Interrupt / Response', '接收 / 拒绝 / 打断 / 响应'],
  ['fast path / cloud FC / Planner', '规则快路 / 云端函数调用模型 / 规划决策器'],
  ['user_query｜P0', '用户请求（user_query）｜P0'],
  ['advisor｜P1', '顾问建议（advisor）｜P1'],
  ['tool_feedback', '工具执行反馈（tool_feedback）'],
  ['event｜P1', '系统事件（event）｜P1'],
  ['Goal / Task-triggered input', '目标 / 任务触发输入'],
  ['query / advice / result / event', '请求 / 建议 / 结果 / 事件'],
  ['allow / confirm / deny / degrade', '允许 / 确认 / 拒绝 / 降级'],
  ['ACK / ASK / PROGRESS / FINAL', '确认 / 追问 / 进度 / 最终答复'],
  ['continue / replan / wait / end', '继续 / 改计划 / 等待 / 结束'],

  ['Decision Parser', '决策结果解析器'],
  ['Action Schema', '动作字段校验'],
  ['DAG Scheduler', '依赖图调度器'],
  ['timeout / retry / cancel / partial', '超时 / 重试 / 取消 / 部分成功'],
  ['GUI Agent Executor', '界面任务代理执行器'],
  ['Raw Result', '原始执行结果'],
  ['ack / data / error / artifact', '受理 / 数据 / 错误 / 产物'],
  ['Observed State', '真实状态回读'],
  ['device / provider / task state', '设备 / 服务商 / 任务状态'],
  ['Result Normalizer', '结果标准化'],
  ['status / error / retryable / partial', '状态 / 错误 / 可否重试 / 部分成功'],
  ['Same Planner · Next Round', '同一规划决策器｜下一轮'],
  ['continue / replan / ask / wait / end', '继续 / 改计划 / 追问 / 等待 / 结束'],
  ['TTS', '语音合成（TTS）'],
  ['online / offline / S2S', '在线 / 离线 / 端到端语音'],
  ['HMI / Avatar', '人机界面 / 助手形象'],
  ['vehicle / nav / media / service', '车辆 / 导航 / 媒体 / 外部服务'],

  ['IDENTITY / PERCEPTION PORTAL', '身份 / 感知接入点'],
  ['CONTEXT / MEMORY PORTAL', '上下文 / 记忆接入点'],
  ['query/advisor/feedback/event', '请求 / 顾问 / 反馈 / 事件'],
  ['user + talk + action + feedback', '用户原话＋回复＋动作＋反馈'],
  ['vehicle/nav/media/app', '车辆 / 导航 / 媒体 / 应用'],
  ['latest scene + dynamic topic', '最新场景＋动态观察主题'],
  ['sensor/manual/reject/trigger', '传感 / 手动 / 拒识 / 触发'],
  ['face/account/seat/privacy', '人脸 / 账号 / 座位 / 隐私'],
  ['status/progress/pending', '状态 / 进度 / 待处理'],
  ['weather/web/POI fresh facts', '天气 / 网页 / 地点最新事实'],
  ['manual/knowhow/vehicle spec', '说明书 / 技巧 / 车型规格'],
  ['schema/capability/version', '字段 / 能力 / 版本'],
  ['role/style/value boundary', '角色 / 风格 / 价值边界'],
  ['date/location/model/connectivity', '日期 / 位置 / 车型 / 网络'],
  ['source / user / vehicle / session', '来源 / 用户 / 车辆 / 会话'],
  ['timestamp / TTL / stale', '时间戳 / 有效期 / 陈旧'],
  ['fact / advice / result / hypothesis', '事实 / 建议 / 结果 / 假设'],
  ['PLANNER CAPABILITY PORTAL', '规划决策器能力接入点'],
  ['seat→vehicle_status→vehicle_control', '座位 → 车辆状态查询 → 车控'],
  ['vehicle control + observed state', '车控执行＋真实状态回读'],

  ['DOWNLINK｜from 05 Decision Bridge', '动作下行｜来自 05 确定性决策桥'],
  ['Ready ToolCall / AgentGoal', '已通过门禁的工具调用 / 任务代理目标'],
  ['tool_name selects one card', '工具名称选择一个具体能力'],
  ['RESULT OUT', '结果汇出'],
  ['vehicle result', '车辆执行结果'],
  ['nav / booking result', '导航 / 交易结果'],
  ['media / artifact', '媒体状态 / 生成产物'],
  ['fact / observation', '事实 / 观察结果'],
  ['identity / goal state', '身份 / 目标状态'],
  ['Adapter / SDK / Protocol', '适配器 / 软件开发包 / 协议'],
  ['correlation + late-result protection', '结果关联＋迟到保护'],
  ['Agent / GUI Runtime', '任务代理 / 界面运行时'],
  ['internal steps + progress + final', '内部步骤＋进度＋终态'],
  ['FEEDBACK_UPLINK', '执行反馈上行总线'],
  ['tool_feedback → main 07 / same Planner', '工具执行反馈 → 主链 07 → 同一规划决策器'],
  ['PRESENTATION HOOK', '界面呈现挂接点'],
  ['native UI / card / artifact / tool speech', '原生界面 / 卡片 / 产物 / 工具自播'],

  ['create / update / delete', '创建 / 更新 / 删除'],
  ['Goal List', '目标队列（Goal List）'],
  ['goal_id / condition / status / scope', '目标编号 / 条件 / 状态 / 范围'],
  ['RuleSpec / Subscription', '规则定义 / 订阅'],
  ['time / signal / VLM / event condition', '时间 / 信号 / 视觉 / 事件条件'],
  ['dedupe / debounce / retry / cancel', '去重 / 防抖 / 重试 / 取消'],
  ['goal review / advice', '目标复盘 / 顾问建议'],
  ['full watch list + version', '全量观察清单＋版本'],
  ['AlwaysOn snapshot', '常驻视觉快照'],
  ['objective report', '客观观察报告'],
  ['task number + text + time', '任务编号＋描述＋时间'],
  ['Topic Split', '观察主题分流'],
  ['default scene / dynamic task', '默认场景 / 动态任务'],
  ['task_manage / GUI API', '任务管理接口 / 界面接口'],
  ['Task Agent', '任务代理（Task Agent）'],
  ['pure entry / passthrough', '仅做入口 / 透传'],
  ['Task Ingress', '任务入口层'],
  ['parse / bind / idempotency', '解析 / 绑定 / 幂等'],
  ['Spec Builder', '任务规格构建器'],
  ['create/update/cancel/query', '创建 / 更新 / 取消 / 查询'],
  ['Task Manager', '任务服务内的任务管理器'],
  ['deterministic lifecycle', '确定性生命周期'],
  ['Task/Run/Event Repo', '任务 / 运行 / 事件事实仓库'],
  ['source of truth + binding', '唯一事实源＋全链绑定'],
  ['Trigger Adapter', '触发适配器'],
  ['reuse existing RuleSpec', '复用既有规则定义'],
  ['Trigger', '触发器（Trigger）'],
  ['time/signal/VLM → callback', '时间 / 信号 / 视觉 → 回调'],
  ['Callback → Ingress', '回调 → 任务入口层'],
  ['restore task + dedupe', '恢复任务＋去重'],
  ['Activate + Create Run', '激活任务＋创建本轮运行'],
  ['waiting → running', '等待 → 运行中'],
  ['Execution Guard', '执行前门禁'],
  ['latest context / safety', '最新上下文 / 安全条件'],
  ['Runtime Dispatcher', '本轮运行调度器'],
  ['general / ecosystem', '通用链路 / 生态链路'],
  ['Original Flow / Planner', '原流程 / 同一规划决策器'],
  ['beforeFlow → same main chain', '进入原流程 → 同一主链'],
  ['Result Hook', '独立结果钩子'],
  ['AgentObservation / Tool result', '任务代理观察 / 工具结果'],
  ['HandleRunResult', '处理本轮运行结果'],
  ['transaction + compensation', '事务写回＋失败补偿'],
  ['TaskMessage', '任务消息'],
  ['HMI / SSE / center', '人机界面 / 服务端推送 / 任务中心'],

  ['System Prompt', '系统提示词（SP）'],
  ['User Prompt', '用户提示词（UP）'],
  ['LLM Inference｜Planner = Director', '大模型推理｜Planner 与 Director 是同一模块'],
  ['Capability Registry', '能力注册表'],
  ['what can run where', '什么能力能在哪种环境运行'],
  ['schema / owner / side effect / SLA', '字段契约 / 负责人 / 副作用 / 服务级目标'],
  ['protocol mapping → underlying module / service', '协议映射 → 底层模块 / 服务'],
  ['readback / provider state', '状态回读 / 服务商状态'],
  ['Completion Aggregator', '完成状态聚合器'],
  ['pending / partial / failed / done', '待处理 / 部分成功 / 失败 / 完成'],
  ['Response Coordinator', '回复与输出协调器'],
  ['perception / confirmation / execution / local trigger', '感知 / 确认 / 执行 / 端侧触发'],
  ['every failure should become evidence', '每个失败都必须形成下一轮可用证据'],
  ['AlwaysOn / Watcher', '常驻观察器'],
  ['continuous multimodal listening', '持续多模态观察'],
  ['event point → trigger → temporal processing', '事件点 → 触发 → 时序加工'],
  ['face feature', '人脸特征'],
  ['identity key', '身份主键'],
  ['identity ≠ authorization', '身份识别不等于操作授权'],
  ['preprocess / fuse / serialize', '预处理 / 融合 / 序列化'],
  ['recognize / describe / parse', '识别 / 描述 / 解析'],
  ['query / event / context fact / dynamic report', '请求 / 事件 / 上下文事实 / 动态观察报告'],
  ['Memory class', '记忆分类'],
  ['AI capability checkpoint', 'AI 能力检查点'],
  ['AI judgement ≠ deterministic guarantee', 'AI 判断不等于确定性保证'],
  ['repeatability + goal completion', '稳定性＋用户完整目标完成'],
  ['A done + B playing + C route / POI state + D scheduled / later verified', 'A 已完成＋B 正在播放＋C 路线/沿途地点状态＋D 已设置/稍后验真'],
  ['Tool lifecycle', '工具调用生命周期'],
  ['READY → CALLING → RESULT', '就绪 → 调用中 → 返回结果'],
  ['result / error / state / artifact', '结果 / 错误 / 状态 / 产物'],
  ['Agent lifecycle', '任务代理生命周期'],
  ['goal → steps → terminal', '目标 → 内部步骤 → 终态'],
  ['progress / need_user_input', '进度 / 需要用户补充'],
  ['artifact / final / blocked', '产物 / 最终结果 / 受阻'],
  ['accepted ≠ called ≠ effected ≠ completed', '已接收 ≠ 已调用 ≠ 已生效 ≠ 完整目标已完成'],
  ['Result Normalizer / Feedback Contract', '结果标准化 / 执行反馈契约'],
  ['raw → {status,data,error,retryable,observed_state,artifact,spoken_content}', '原始结果 → 状态 / 数据 / 错误 / 可否重试 / 真实状态 / 产物 / 已播内容'],
  ['receive one call → execute → expose observable state', '接收一次调用 → 执行 → 暴露可观测状态'],
  ['Observed State / AgentObservation', '真实状态 / 任务代理观察'],
  ['what actually happened', '实际发生了什么'],
  ['raw result → planner-consumable feedback', '原始结果 → 规划决策器可消费的反馈'],
  ['per-action evidence → composite goal state', '单动作证据 → 复合目标状态'],
  ['Default Topic → Context', '默认观察主题 → 上下文'],
  ['latest visual scene', '最新视觉场景'],
  ['CONTEXT_TOPIC Portal', '上下文观察主题入口'],
  ['task number → original watch goal', '任务编号 → 原始观察目标'],
  ['objective report + RuleSpec → Yes / No / Unknown', '客观报告＋规则定义 → 是 / 否 / 未知'],
  ['VQA ≠ default AlwaysOn ≠ dynamic watch', '按需视觉问答 ≠ 默认常驻视觉 ≠ 动态长期观察'],
  ['dynamic VLM report ≠ business decision', '动态视觉报告不等于业务决策'],
  ['Task: waiting → running → closed', '任务：等待 → 运行中 → 已关闭'],
  ['Task close_reason：finished / canceled / expired / failed / vehicle_offline', '任务关闭原因：完成 / 取消 / 过期 / 失败 / 车辆离线'],
  ['Run：running → succeeded / failed / skipped / canceled', '本轮运行：运行中 → 成功 / 失败 / 跳过 / 取消'],
  ['Run phase：executing / waiting_user_confirmation / waiting_client / waiting_external', '本轮阶段：执行中 / 等用户确认 / 等车端 / 等外部服务'],
  ['mastery checkpoint', '掌握度检查点'],

  ['utterance', '原始话语'],
  ['offline', '离线'],
  ['online final', '在线最终结果'],
  ['fallback', '降级'],
  ['asr_final', '语音识别最终文本'],
  ['identity candidate', '身份候选'],
  ['trace', '链路追踪'],
  ['interaction', '是否介入'],
  ['accepted', '已接收'],
  ['reject / ignore', '拒绝 / 忽略'],
  ['local whitelist', '端侧白名单'],
  ['simple', '简单任务'],
  ['complex', '复杂任务'],
  ['accepted input', '已接纳输入'],
  ['fixed SP', '固定系统提示词'],
  ['typed prompt', '类型化提示词'],
  ['validated candidate', '通过校验的候选结果'],
  ['PlannerDecision', '规划决策结果'],
  ['ready', '可下发'],
  ['ToolCall / AgentGoal', '工具调用 / 任务代理目标'],
  ['atomic call', '原子调用'],
  ['steps / progress', '步骤 / 进度'],
  ['raw result + state', '原始结果＋真实状态'],
  ['normalized', '已标准化'],
  ['next input', '下一轮输入'],
  ['evidence', '完成证据'],
  ['speech', '语音'],
  ['visual', '界面 / 形象'],
  ['hear', '用户听到'],
  ['real effect', '真实生效'],
  ['feature match', '特征匹配'],
  ['bind', '绑定'],
  ['account relation', '账号关联'],
  ['session identity', '会话身份'],
  ['authorize / isolate', '授权 / 隔离'],
  ['context sources', '上下文事实来源'],
  ['filtered PlannerView', '筛选后的规划决策视图'],
  ['parallel', '并行'],
  ['serial', '串行'],
  ['address', '地址'],
  ['route ready', '路线已就绪'],
  ['async', '异步'],
  ['timer', '定时器'],
  ['wake + execute', '唤醒并执行'],
  ['DOWNLINK', '动作下行'],
  ['ToolCall bus', '工具调用总线'],
  ['result + state', '结果＋真实状态'],
  ['normalized states', '标准化状态'],
  ['feedback', '执行反馈'],
  ['display hook', '呈现挂接'],
  ['FEEDBACK_UPLINK → 07 Result Loop', '执行反馈上行 → 主链 07 结果闭环'],
  ['persist', '持久化'],
  ['subscribe', '注册订阅'],
  ['wait', '等待'],
  ['hit callback', '命中回调'],
  ['if routed to cloud', '适用时回到云端主链'],
  ['replace full list', '覆盖式下发全量清单'],
  ['cycle', '周期采样'],
  ['description', '客观描述'],
  ['default', '默认观察'],
  ['dynamic', '动态观察'],
  ['callback must return to Ingress', '回调必须先回任务入口层'],

  ['vehicle_basic_control', '基础车控（vehicle_basic_control）'],
  ['vehicle_system_settings', '车载系统设置（vehicle_system_settings）'],
  ['vehicle_communication', '车载通信（vehicle_communication）'],
  ['auto_drive', '辅助驾驶控制（auto_drive）'],
  ['ambient_light_control', '氛围灯控制（ambient_light_control）'],
  ['navi_basic_control', '导航过程控制（navi_basic_control）'],
  ['media_basic_control', '当前媒体控制（media_basic_control）'],
  ['vehicle_status_search', '车辆实时状态查询（vehicle_status_search）'],
  ['weather_search', '天气查询（weather_search）'],
  ['poi_search', '地点与商家搜索（poi_search）'],
  ['web_search', '联网信息搜索（web_search）'],
  ['car_log', '用车报告查询（car_log）'],
  ['vehicle_manual_qa', '车辆说明书问答（vehicle_manual_qa）'],
  ['car_care_qa', '车况维养问答（car_care_qa）'],
  ['visual_qa', '当前视觉问答（visual_qa）'],
  ['user_memory_search', '用户记忆查询（user_memory_search）'],
  ['route_planning', '路线规划并发起导航（route_planning）'],
  ['video_search', '视频搜索并播放（video_search）'],
  ['music_search', '音乐搜索并播放（music_search）'],
  ['broadcast_search', '播客搜索并播放（broadcast_search）'],
  ['face_id_register', '人脸身份注册（face_id_register）'],
  ['user_memory_operate', '用户记忆写入/纠正/删除（user_memory_operate）'],
  ['goal_list_update', '持续目标管理（goal_list_update）'],
  ['ai_broadcast_generate', '人工智能播客生成（ai_broadcast_generate）'],
  ['image_generate', '图片生成与编辑（image_generate）'],
  ['audio_record', '录音纪要（audio_record）'],
  ['restaurant_reserve', '停车缴费（parking_fee_pay）'],

  ['WRITE · params.query', '写操作｜参数 query'],
  ['WRITE · system / UI', '写操作｜系统 / 界面'],
  ['WRITE · call / video', '写操作｜电话 / 视频通话'],
  ['WRITE · ADAS / parking', '写操作｜辅助驾驶 / 泊车'],
  ['WRITE · light', '写操作｜灯光'],
  ['READ · POI list', '只读｜地点候选'],
  ['READ+WRITE · route', '搜索并执行｜路线 / 导航'],
  ['WRITE · nav state', '写操作｜当前导航状态'],
  ['TRANSACTION · booking', '交易｜停车缴费'],
  ['SEARCH+PLAY · video', '搜索并播放｜视频'],
  ['SEARCH→AUTO PLAY', '搜索后自动播放'],
  ['WRITE · current media', '写操作｜当前媒体'],
  ['ASYNC · generation', '异步｜内容生成'],
  ['SEARCH+PLAY · podcast', '搜索并播放｜播客'],
  ['WRITE+ASYNC · record', '写操作＋异步产物｜录音纪要'],
  ['ASYNC AIGC · query / type', '异步图片生成｜描述 / 类型'],
  ['READ · live vehicle', '只读｜本车实时状态'],
  ['READ · real-time weather', '只读｜实时天气'],
  ['READ · open web', '只读｜开放互联网'],
  ['READ · vehicle history', '只读｜车辆历史'],
  ['READ · general manual', '只读｜通用说明书'],
  ['READ · VIN-specific', '只读｜当前车辆专属信息'],
  ['READ · live vision', '只读｜当前视觉'],
  ['READ · private memory', '只读｜用户私有记忆'],
  ['WRITE · identity', '写操作｜身份数据'],
  ['WRITE · memory', '写操作｜用户记忆'],
  ['WRITE · long-running goal', '写操作｜持续目标'],

  ['输入：预订/查询/修改/取消 + 餐厅/时间/人数', '输入：停车缴费请求＋车牌 / 车辆信息'],
  ['机制：缺手机号等返回补槽，补齐后再次调用', '机制：确认车牌 → 注册或续费 → 查询订单 → 返回金额与付款地址'],
  ['输出：订单号 / 状态 / 失败原因', '输出：订单、应付金额、付款地址与展示状态'],
  ['门禁：不得重复问已有字段；错订为高风险', '门禁：车牌和金额确认；订单幂等；支付成功必须有回调证据'],
  ['nav / booking result', '导航 / 交易结果'],

  ['Seed 1.8 · [SP,UP]', '豆包 Seed 1.8｜系统提示词＋用户提示词'],
  ['user_query', '用户请求（user_query）'],
  ['OMS / DMS / AlwaysOn', '舱内监测 / 驾驶员监测 / 常驻观察'],
  ['Planner', '规划决策器（Planner）'],
  ['M4｜Tool / Agent / Executor / Async', 'M4｜工具 / 任务代理 / 执行器 / 异步任务'],
  ['Planner SP snapshot · 2026-07-31', '规划决策器提示词快照｜2026-07-31'],
  ['CURRENT / CONFIRMED / TRACE / HISTORY / WIP / RISK', '当前 / 已确认 / 待链路验真 / 历史 / 建设中 / 风险'],
  ['Query Envelope', '用户请求封装'],
  ['user_query{query,speaker_name,speaker_position,timestamp}', '用户请求字段：内容 / 说话人 / 座位 / 时间'],
  ['permission / wake / cut / noise / network', '权限 / 唤醒 / 截断 / 噪声 / 网络'],
  ['classify → priority → interrupt / merge / queue / drop', '分类 → 优先级 → 打断 / 合并 / 排队 / 丢弃'],
  ['Context Selector', '上下文筛选器'],
  ['select → isolate → fresh → resolve → summarize', '选择 → 隔离 → 新鲜度 → 冲突裁决 → 摘要'],
  ['ContextSnapshot', '本轮上下文快照'],
  ['single decision view', '本轮唯一决策事实视图'],
  ['current input', '当前输入'],
  ['identity / seat / privacy', '身份 / 座位 / 隐私'],
  ['dialogue / scene / state / memory', '对话 / 场景 / 状态 / 记忆'],
  ['goal / tool availability / facts', '目标 / 工具可用性 / 事实'],
  ['~30K–35K tokens · local snapshot', '约 3万–3.5万词元｜本地快照'],
  ['~10K–15K tokens · local snapshot', '约 1万–1.5万词元｜本地快照'],
  ['ContextSnapshot / Goal / prior feedback', '上下文快照 / 目标 / 历史反馈'],
  ['{talk_or_not, talk_content, emoji_id?, action_list:[{action_id?,tool_name,params}]}', '输出字段：是否说话 / 回复内容 / 形象动作 / 动作清单（动作编号＋工具名＋参数）'],
  ['Dispatch Envelope', '执行调度封装'],
  ['request / turn / action / trace + tool_name + params', '请求 / 轮次 / 动作 / 追踪编号＋工具名＋参数'],
  ['typed schema → one call', '强类型字段 → 一次原子调用'],
  ['goal → internal steps', '目标 → 内部执行步骤'],
  ['face_id', '人脸身份编号（face_id）'],
  ['vehicle account', '车辆账号'],
  ['Doubao account', '豆包账号'],
  ['speaker + position', '说话人＋座位'],
  ['CURRENT_INPUT + IDENTITY + STATE + SCENE + MEMORY + GOAL + TOOLS + KNOWLEDGE', '当前输入＋身份＋状态＋场景＋记忆＋目标＋工具＋知识'],
  ['goal + context + registry → tool_name / agent type + params', '目标＋上下文＋能力注册表 → 工具名 / 任务代理类型＋参数'],
  ['request_id / turn_id / action_id / task_id / run_id', '请求编号 / 轮次编号 / 动作编号 / 任务编号 / 运行编号'],
  ['Agent：step / progress / need_user / final', '任务代理：步骤 / 进度 / 需要用户补充 / 最终结果'],
  ['create / merge / supplement / close', '创建 / 合并 / 补充 / 关闭'],
  ['tool_feedback + observed state', '工具执行反馈＋真实状态'],
  ['task_id / run_id / callback_id / recommend_id / request_id / log_id', '任务编号 / 运行编号 / 回调编号 / 建议编号 / 请求编号 / 日志编号'],
  ['WIP Portal：PLANNER_INPUT / TRIGGER_CALLBACK / RESULT_HOOK / CONTEXT_TOPIC', '建设中入口：规划输入 / 触发回调 / 结果钩子 / 上下文主题'],
  ['WIP', '建设中'],
  ['GO', '两年成果'],
  ['SRC', '证据边界'],
  ['LOCAL SP + PRD / TRANSCRIPT + 3 FEISHU ARCHITECTURE BOARDS · audited 2026-09-03', '版本不一致时以当前提示词、正式方案、逐字稿和链路追踪为准，不把历史设计写成现状'],
  ['goal_id', '目标编号'],
  ['3｜工具 / 任务代理 / 执行器能力层｜27 个工具逐项展开', '3｜工具 / 任务代理 / 执行器能力层｜27 个工具（9 月配置表口径）'],
  ['该快照含 27 工具；旧资料另有 23 / 18 / 30 口径，必须绑定版本', '工具目录按 9 月配置表的 27 项排列；决策协议按当前提示词与正式方案复核'],
  ['Planner=Director；“27”不代表历史版本或线上部署永远一致', '规划决策器即内部 Director；工具数量与名称必须随版本记录，不混用历史口径'],
  ['角色 / 输入类型 / 27 工具 / 输出格式', '角色 / 输入类型 / 工具注册表 / 输出协议'],
]);

const escapeXml = value => value
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&apos;');

for (const [from, to] of replacements) {
  const encodedFrom = escapeXml(from);
  const encodedTo = escapeXml(to);
  const needle = `>${encodedFrom}</text>`;
  svg = svg.split(needle).join(`>${encodedTo}</text>`);
}

// Re-number the 27 visible tool cards to the latest 9月配置表 sequence. These labels are
// presentation numbers only; XML element ids and routing relationships are unchanged.
const numberMap = new Map([
  ['T01', '01'], ['T02', '02'], ['T03', '03'], ['T19', '04'], ['T20', '05'],
  ['T08', '06'], ['T11', '07'], ['T04', '08'], ['T05', '09'], ['T06', '10'],
  ['T15', '11'], ['T21', '12'], ['T22', '13'], ['T23', '14'], ['T26', '15'],
  ['T12', '16'], ['T07', '17'], ['T09', '18'], ['T10', '19'], ['T18', '20'],
  ['T13', '21'], ['T14', '22'], ['T16', '23'], ['T17', '24'], ['T25', '25'],
  ['T24', '26'], ['T27', '27'],
]);
for (const [from, to] of numberMap) {
  svg = svg.replace(new RegExp(`>${from}</text>`, 'g'), `>${to}</text>`);
}

await writeFile(output, svg, 'utf8');
console.log(JSON.stringify({ input, output, replacements: replacements.size, toolNumbers: numberMap.size }, null, 2));
