import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire('/Users/bytedance/.npm/_npx/12f3a93219d134f5/node_modules/jsdom/package.json');
const {JSDOM,VirtualConsole}=require('jsdom');
const root='/Users/bytedance/Desktop/3.23';
const base=root+'/whiteboard/豆包汽车-业务全链路-v13';
const file=root+'/产品/codex/HTML/02-已交付/豆包汽车-全链路来源与模块核对-v01.html';
const html=fs.readFileSync(file,'utf8'),cross=JSON.parse(fs.readFileSync(base+'/module-crosswalk.json','utf8'));
const errs=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errs.push(e.message));
const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://artifact.invalid/',virtualConsole:vc});
const d=dom.window.document;
const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size,'duplicate id');
for(const a of d.querySelectorAll('a[href^="#"]'))assert(d.getElementById(a.getAttribute('href').slice(1)),'broken anchor '+a.getAttribute('href'));
assert.equal(d.querySelectorAll('.node-row').length,235);
assert.equal(d.querySelectorAll('[data-original]').length,30);
assert.equal(d.querySelectorAll('[data-tool]').length,27);
assert.equal(cross.groupAudit.length,23);
assert.equal(cross.sources.length,14);
assert(cross.sources.find(x=>x.id==='S07').state==='读取不全');
assert(cross.sources.find(x=>x.id==='S13').state==='无权限');
assert.equal(d.querySelectorAll('.finding').length,12);
for(const n of cross.nodeAudit)assert(Array.isArray(n.to));
const input=d.querySelector('#search');input.value='发布校验';input.dispatchEvent(new dom.window.Event('input'));
assert.equal(d.querySelector('#group-config').hidden,false);assert(d.querySelector('#group-config details').open);
assert(d.querySelectorAll('.audit-item[hidden]').length>0);
d.querySelector('#clear').click();assert.equal(d.querySelectorAll('.audit-item[hidden]').length,0);
d.querySelector('#expand').click();assert.equal(d.querySelectorAll('.node-detail[open]').length,23);
const sp=JSON.parse(fs.readFileSync(root+'/产品/1-原始素材/资料数据PRD原件/planner 架构/动态示例/sp.md','utf8')).content;
const actual=[...sp.matchAll(/【工具名称】\s*([a-z_]+)/g)].map(m=>m[1]);
assert.equal(new Set(actual).size,27);assert.deepEqual([...new Set(actual)].sort(),cross.tools.map(t=>t.name).sort());
assert.equal(d.querySelectorAll('img,iframe,link[rel="stylesheet"],script[src]').length,0,'unexpected external resources');
assert.deepEqual(errs,[]);
const report={html:file,checks:{oldNodes:235,oldNumberedModules:30,groups:23,toolDefinitions:27,toolNamesMatchLocalSP:true,sourceLedger:14,newFindings:12,anchors:true,search:true,expandCollapse:true,sourceGapsExplicit:true,noExternalResources:true},mode:'DOM/内容一致性检查；不等于真实浏览器视觉验收',errors:errs};
fs.writeFileSync(base+'/audit-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));dom.window.close();
