#!/bin/bash
# 一键还原:把所有文件移回原位
cd '/Users/bytedance/Desktop/3.23/产品-端侧触发器'
mv -n '1-原始素材/会议纪要/2 次会议纪要.md' '2 次会议纪要.md'
mv -n '../_系统生成/3.23-file-action-dashboard.html' '3.23-file-action-dashboard.html'
mv -n '../_系统生成/3.23-file-action-summary.json' '3.23-file-action-summary.json'
mv -n '../_系统生成/3.23-file-dedup-dashboard.html' '3.23-file-dedup-dashboard.html'
mv -n '../_系统生成/3.23-file-dedup-summary.json' '3.23-file-dedup-summary.json'
mv -n '1-原始素材/会议纪要/6.22会议.md' '6.22会议.md'
mv -n '2-AI产出-最新/地图手册综合/6.22评审复盘.html' '6.22评审复盘.html'
mv -n '1-原始素材/会议纪要/616.会议纪要.md' '616.会议纪要.md'
mv -n '2-AI产出-最新/需求详解PRD/PRD逻辑梳理与TODO整理.docx' 'PRD逻辑梳理与TODO整理.docx'
mv -n '3-AI产出-旧版归档/PRD逻辑梳理与TODO整理.html' 'PRD逻辑梳理与TODO整理.html'
mv -n '2-AI产出-最新/需求详解PRD/VLM场景PRD.html' 'VLM场景PRD.html'
mv -n '1-原始素材/资料数据PRD原件/advisor-事件&context.xlsx' 'advisor-事件&context.xlsx'
mv -n '../_系统生成/bug fenxi.md' 'bug fenxi.md'
mv -n '../_系统生成/duplicate_cleanup_strict_audit_2026-06-21.html' 'duplicate_cleanup_strict_audit_2026-06-21.html'
mv -n '../_系统生成/duplicate_cleanup_strict_audit_2026-06-21.json' 'duplicate_cleanup_strict_audit_2026-06-21.json'
mv -n '../_系统生成/duplicate_cleanup_strict_audit_2026-06-21.md' 'duplicate_cleanup_strict_audit_2026-06-21.md'
mv -n '../_系统生成/duplicate_cleanup_verification_2026-06-21.html' 'duplicate_cleanup_verification_2026-06-21.html'
mv -n '../_系统生成/duplicate_cleanup_verification_2026-06-21.json' 'duplicate_cleanup_verification_2026-06-21.json'
mv -n '1-原始素材/资料数据PRD原件/【AICar】端侧VLM任务优先级.md' '【AICar】端侧VLM任务优先级.md'
mv -n '1-原始素材/资料数据PRD原件/【AI汽车】端侧视觉感知.html' '【AI汽车】端侧视觉感知.html'
mv -n '1-原始素材/资料数据PRD原件/【DNA1.0】PRD_豆包车载机器人_D6X_V12.0.html' '【DNA1.0】PRD_豆包车载机器人_D6X_V12.0.html'
mv -n '1-原始素材/资料数据PRD原件/【上汽DNA - AI汽车 1.0 - IS4PR】场景感知状态信号库v2.5.xlsx' '【上汽DNA - AI汽车 1.0 - IS4PR】场景感知状态信号库v2.5.xlsx'
mv -n '1-原始素材/资料数据PRD原件/【上汽DNA - AI汽车 1.0 - IS4PR】车控车设需求开发集成验证 (1).xlsx' '【上汽DNA - AI汽车 1.0 - IS4PR】车控车设需求开发集成验证 (1).xlsx'
mv -n '2-AI产出-最新/需求详解PRD/主动服务-Attention触发器-需求.html' '主动服务-Attention触发器-需求.html'
mv -n '1-原始素材/会议纪要/会议影响分析-6.11端侧触发器.html' '会议影响分析-6.11端侧触发器.html'
mv -n '1-原始素材/会议纪要/会议纪要.md' '会议纪要.md'
mv -n '1-原始素材/会议纪要/会议记录 2.md' '会议记录 2.md'
mv -n '1-原始素材/会议纪要/会议记录 3.md' '会议记录 3.md'
mv -n '1-原始素材/会议纪要/会议记录.md' '会议记录.md'
mv -n '2-AI产出-最新/地图手册综合/名下问题梳理_王泽民_上报版_20260603.md' '名下问题梳理_王泽民_上报版_20260603.md'
mv -n '_待归类/明日评审-端云触发器大图.png' '明日评审-端云触发器大图.png'
mv -n '2-AI产出-最新/讲解稿话术/明日评审-触发器口播救场版.html' '明日评审-触发器口播救场版.html'
mv -n '3-AI产出-旧版归档/架构与流程详解 - 评审讲稿.md' '架构与流程详解 - 评审讲稿.md'
mv -n '3-AI产出-旧版归档/架构与流程详解 - 逐字评审稿.md' '架构与流程详解 - 逐字评审稿.md'
mv -n '_待归类/架构图_会议修正版.png' '架构图_会议修正版.png'
mv -n '2-AI产出-最新/地图手册综合/泽民工作地图.html' '泽民工作地图.html'
mv -n '2-AI产出-最新/图-流程架构/端云协同触发器-完整业务架构.html' '端云协同触发器-完整业务架构.html'
mv -n '2-AI产出-最新/图-流程架构/端云触发器_全资料版评审大图.html' '端云触发器_全资料版评审大图.html'
mv -n '2-AI产出-最新/图-流程架构/端云触发器_全资料版评审大图.png' '端云触发器_全资料版评审大图.png'
mv -n '3-AI产出-旧版归档/端云触发器_评审架构图.md' '端云触发器_评审架构图.md'
mv -n '3-AI产出-旧版归档/端云触发器_评审架构大图.html' '端云触发器_评审架构大图.html'
mv -n '_待归类/端云触发器架构图-原图增强评审版.png' '端云触发器架构图-原图增强评审版.png'
mv -n '_待归类/端云触发器架构图-核对修正版.png' '端云触发器架构图-核对修正版.png'
mv -n '3-AI产出-旧版归档/端侧触发器 - PRD.html' '端侧触发器 - PRD.html'
mv -n '3-AI产出-旧版归档/端侧触发器 - PRD.md' '端侧触发器 - PRD.md'
mv -n '1-原始素材/资料数据PRD原件/端侧触发器 - PRD（会议修改版）.html' '端侧触发器 - PRD（会议修改版）.html'
mv -n '3-AI产出-旧版归档/端侧触发器 - PRD（完整版）.docx' '端侧触发器 - PRD（完整版）.docx'
mv -n '3-AI产出-旧版归档/端侧触发器 - PRD（完整版）.html' '端侧触发器 - PRD（完整版）.html'
mv -n '2-AI产出-最新/需求详解PRD/端侧触发器 - PRD（整理版）.html' '端侧触发器 - PRD（整理版）.html'
mv -n '3-AI产出-旧版归档/端侧触发器 - PRD（补充版）.md' '端侧触发器 - PRD（补充版）.md'
mv -n '3-AI产出-旧版归档/端侧触发器 - 完整PRD.md' '端侧触发器 - 完整PRD.md'
mv -n '3-AI产出-旧版归档/端侧触发器 - 评审会逐字稿.docx' '端侧触发器 - 评审会逐字稿.docx'
mv -n '3-AI产出-旧版归档/端侧触发器 - 评审讲稿.md' '端侧触发器 - 评审讲稿.md'
mv -n '1-原始素材/资料数据PRD原件/端侧触发器需求全景讲解.md' '端侧触发器需求全景讲解.md'
mv -n '1-原始素材/资料数据PRD原件/端侧触发器需求评审会讲稿.md' '端侧触发器需求评审会讲稿.md'
mv -n '1-原始素材/资料数据PRD原件/触发器 DSL 定义【对外】.html' '触发器 DSL 定义【对外】.html'
mv -n '2-AI产出-最新/图-流程架构/触发器-业务流程-query到输出.html' '触发器-业务流程-query到输出.html'
mv -n '2-AI产出-最新/图-流程架构/触发器-业务流程-全模块大图-v2.html' '触发器-业务流程-全模块大图-v2.html'
mv -n '3-AI产出-旧版归档/触发器-业务流程-全模块大图.html' '触发器-业务流程-全模块大图.html'
mv -n '2-AI产出-最新/讲解稿话术/触发器-业务流程-讲解稿.md' '触发器-业务流程-讲解稿.md'
mv -n '2-AI产出-最新/地图手册综合/触发器-交付物作战手册.md' '触发器-交付物作战手册.md'
mv -n '2-AI产出-最新/地图手册综合/触发器-刘杨沟通准备.md' '触发器-刘杨沟通准备.md'
mv -n '2-AI产出-最新/需求详解PRD/触发器-端云职责与五方关系-详解.html' '触发器-端云职责与五方关系-详解.html'
mv -n '2-AI产出-最新/图-流程架构/触发器-骨架图与流程图.html' '触发器-骨架图与流程图.html'
mv -n '2-AI产出-最新/图-流程架构/触发器Condition-Trigger-Action.html' '触发器Condition-Trigger-Action.html'
mv -n '2-AI产出-最新/需求详解PRD/触发器PRD-v2.html' '触发器PRD-v2.html'
mv -n '2-AI产出-最新/地图手册综合/触发器Planner转具身智能_能力迁移图谱.html' '触发器Planner转具身智能_能力迁移图谱.html'
mv -n '1-原始素材/会议纪要/触发器会议.md' '触发器会议.md'
mv -n '2-AI产出-最新/地图手册综合/触发器作战地图.html' '触发器作战地图.html'
mv -n '2-AI产出-最新/图-流程架构/触发器全景大图-高清5000px.png' '触发器全景大图-高清5000px.png'
mv -n '2-AI产出-最新/图-流程架构/触发器全景大图.html' '触发器全景大图.html'
mv -n '1-原始素材/资料数据PRD原件/触发器接口文档【对外】.html' '触发器接口文档【对外】.html'
mv -n '1-原始素材/资料数据PRD原件/触发器条件库_v4_含API契约.xlsx' '触发器条件库_v4_含API契约.xlsx'
mv -n '2-AI产出-最新/图-流程架构/触发器架构-核对修正版-高清.png' '触发器架构-核对修正版-高清.png'
mv -n '2-AI产出-最新/图-流程架构/触发器架构-核对修正版.html' '触发器架构-核对修正版.html'
mv -n '2-AI产出-最新/图-流程架构/触发器流程图-单独大图.html' '触发器流程图-单独大图.html'
mv -n '2-AI产出-最新/讲解稿话术/触发器流程图-评审讲解稿.html' '触发器流程图-评审讲解稿.html'
mv -n '3-AI产出-旧版归档/触发器流程图-评审讲解稿_去重前备份.html' '触发器流程图-评审讲解稿_去重前备份.html'
mv -n '3-AI产出-旧版归档/触发器流程图-评审讲解稿_合并前备份.html' '触发器流程图-评审讲解稿_合并前备份.html'
mv -n '3-AI产出-旧版归档/触发器流程图-评审讲解稿_局部框版备份.html' '触发器流程图-评审讲解稿_局部框版备份.html'
mv -n '3-AI产出-旧版归档/触发器流程图-评审讲解稿_插入前备份.html' '触发器流程图-评审讲解稿_插入前备份.html'
mv -n '3-AI产出-旧版归档/触发器流程图-评审讲解稿_补表前备份.html' '触发器流程图-评审讲解稿_补表前备份.html'
mv -n '_待归类/触发器流程图_会议修正版.png' '触发器流程图_会议修正版.png'
mv -n '2-AI产出-最新/讲解稿话术/触发器讲解稿-核对修正版.html' '触发器讲解稿-核对修正版.html'
mv -n '2-AI产出-最新/需求详解PRD/触发器需求-全链路详解.html' '触发器需求-全链路详解.html'
mv -n '2-AI产出-最新/需求详解PRD/触发器需求-完整说明-是什么为什么怎么做如何做.md' '触发器需求-完整说明-是什么为什么怎么做如何做.md'
mv -n '2-AI产出-最新/需求详解PRD/触发器需求-逐条详解.md' '触发器需求-逐条详解.md'
mv -n '2-AI产出-最新/地图手册综合/触发器需求作战手册.html' '触发器需求作战手册.html'
mv -n '1-原始素材/会议纪要/评审逐字稿 - 第二次评审.md' '评审逐字稿 - 第二次评审.md'
mv -n '_待归类/资料索引_触发器评审.json' '资料索引_触发器评审.json'
mv -n '1-原始素材/资料数据PRD原件/高频触发条件清单.md' '高频触发条件清单.md'
mv -n '_配套资源(图表脚本)/diagrams' 'diagrams'
mv -n '_配套资源(图表脚本)/diagrams-v2' 'diagrams-v2'
mv -n '_配套资源(图表脚本)/feishu-board' 'feishu-board'
mv -n '_配套资源(图表脚本)/images' 'images'
mv -n '1-原始素材/资料数据PRD原件/端侧触发器 - PRD_2026-05-06 16-28-56' '端侧触发器 - PRD_2026-05-06 16-28-56'
mv -n '_待归类/触发器需求' '触发器需求'
mv -n '_配套资源(图表脚本)/讲解稿-大图' '讲解稿-大图'
mv -n '3-AI产出-旧版归档/触发器讲解稿-核对修正版.html.bak-before-622' '触发器讲解稿-核对修正版.html.bak-before-622'
mv -n '3-AI产出-旧版归档/触发器PRD-v2.html.bak' '触发器PRD-v2.html.bak'
mv -n '3-AI产出-旧版归档/触发器-端云职责与五方关系-详解.html.bak-before-622' '触发器-端云职责与五方关系-详解.html.bak-before-622'
mv -n '3-AI产出-旧版归档/触发器-端云职责与五方关系-详解.html.bak' '触发器-端云职责与五方关系-详解.html.bak'
mv -n '3-AI产出-旧版归档/触发器PRD-v2.html.bak-before-622' '触发器PRD-v2.html.bak-before-622'
mv -n '_apply_prose.py' '/Users/bytedance/Desktop/3.23/产品-端侧触发器/_apply_prose.py'
cd '/Users/bytedance/Desktop/3.23'
mv -n '产品-端侧触发器/1-原始素材/会议纪要/617 会议.md' '617 会议.md'
mv -n '产品-端侧触发器/1-原始素材/资料数据PRD原件/高频触发条件清单_初稿_王泽民.xlsx' '高频触发条件清单_初稿_王泽民.xlsx'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器-导航信号需求-给刘杨.docx' '触发器-导航信号需求-给刘杨.docx'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器-导航信号需求-给刘杨.md' '触发器-导航信号需求-给刘杨.md'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器-导航信号需求-给刘杨.xlsx' '触发器-导航信号需求-给刘杨.xlsx'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器-周会对齐-全项拆解.html' '触发器-周会对齐-全项拆解.html'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器-周会全项拆解-详版.html' '触发器-周会全项拆解-详版.html'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/触发器模块拆解-样板.html' '触发器模块拆解-样板.html'
mv -n '产品-端侧触发器/2-AI产出-最新/需求详解PRD/PRD-触发器导航类事件-详版.html' 'PRD-触发器导航类事件-详版.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/汇报张航-触发器进度与决策-话术.html' '汇报张航-触发器进度与决策-话术.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/汇报张航-逐字话术稿.html' '汇报张航-逐字话术稿.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/找金龙-底层逻辑.html' '找金龙-底层逻辑.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/信号要不到-推进手册-手把手.html' '信号要不到-推进手册-手把手.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/教你写触发逻辑-用你的真实信号.html' '教你写触发逻辑-用你的真实信号.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/决策二深挖-导航接近AB-讲透版.html' '决策二深挖-导航接近AB-讲透版.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/两个清单别再混-讲清楚.html' '两个清单别再混-讲清楚.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/高频触发条件清单-讲清楚.html' '高频触发条件清单-讲清楚.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/周会话术稿-导航触发器-AB决策与格式对齐.html' '周会话术稿-导航触发器-AB决策与格式对齐.html'
mv -n '产品-端侧触发器/2-AI产出-最新/沟通汇报话术/需求4-机器人对需求-面聊作战手册.md' '需求4-机器人对需求-面聊作战手册.md'
mv -n '产品-端侧触发器/2-AI产出-最新/地图手册综合/泽民-上线前问题汇报表.html' '泽民-上线前问题汇报表.html'
mv -n '产品-端侧触发器/_待归类/赛力斯需求全景骨架图_2026-05-31.html' '赛力斯需求全景骨架图_2026-05-31.html'
